<template>
  <v-container>
    <h2 class="text-center">Tabla de Información</h2>
    <v-table>
      <thead>
        <tr>
          <th>Mares</th>
          <th>Ríos</th>
          <th>Desiertos</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Pacífico</td>
          <td>Pánuco</td>
          <td>Chihuahua</td>
        </tr>
        <tr>
          <td>Atlántico</td>
          <td>Papaloapan</td>
          <td>Sonora</td>
        </tr>
      </tbody>
    </v-table>
  </v-container>
</template>
